name: Code Quality

on:
  pull_request:
    branches:
      - main

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.17.0
          registry-url: "https://registry.npmjs.org"

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Skip post-install scripts here, as a malicious
      # script could steal NODE_AUTH_TOKEN.
      - name: Install dependencies
        run: yarn bootstrap --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Lint Commit Messages
        uses: wagoid/commitlint-github-action@v5

      - name: Lint Code
        run: yarn lint

      - name: Typecheck Code
        run: yarn typecheck

      - name: Test Code
        run: yarn test

      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
